# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/quyvan/Desktop/lab2b/lab2b/sbl.xdc

# Block Designs: bd/sbl/sbl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl || ORIG_REF_NAME==sbl} -quiet] -quiet

# IP: bd/sbl/ip/sbl_microblaze_0_0/sbl_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_microblaze_0_0 || ORIG_REF_NAME==sbl_microblaze_0_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_dlmb_v10_0/sbl_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_dlmb_v10_0 || ORIG_REF_NAME==sbl_dlmb_v10_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_ilmb_v10_0/sbl_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_ilmb_v10_0 || ORIG_REF_NAME==sbl_ilmb_v10_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_dlmb_bram_if_cntlr_0/sbl_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==sbl_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_ilmb_bram_if_cntlr_0/sbl_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==sbl_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_lmb_bram_0/sbl_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_lmb_bram_0 || ORIG_REF_NAME==sbl_lmb_bram_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_xbar_0/sbl_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_xbar_0 || ORIG_REF_NAME==sbl_xbar_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_microblaze_0_axi_periph_0/sbl_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_microblaze_0_axi_periph_0 || ORIG_REF_NAME==sbl_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_mdm_1_0/sbl_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_mdm_1_0 || ORIG_REF_NAME==sbl_mdm_1_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_clk_wiz_1_0/sbl_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_clk_wiz_1_0 || ORIG_REF_NAME==sbl_clk_wiz_1_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_rst_clk_wiz_1_100M_0/sbl_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==sbl_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_axi_gpio_0_0/sbl_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_axi_gpio_0_0 || ORIG_REF_NAME==sbl_axi_gpio_0_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_xlconstant_0_0/sbl_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_xlconstant_0_0 || ORIG_REF_NAME==sbl_xlconstant_0_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_xlconstant_1_0/sbl_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_xlconstant_1_0 || ORIG_REF_NAME==sbl_xlconstant_1_0} -quiet] -quiet

# IP: bd/sbl/ip/sbl_axi_gpio_0_1/sbl_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbl_axi_gpio_0_1 || ORIG_REF_NAME==sbl_axi_gpio_0_1} -quiet] -quiet

# XDC: bd/sbl/sbl_ooc.xdc
