# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/quyvan/Desktop/lab2b/lab2b/lab2b.srcs/sources_1/bd/sbl/ip/sbl_ilmb_v10_0/sbl_ilmb_v10_0.xci
# IP: The module: 'sbl_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/quyvan/Desktop/lab2b/lab2b/lab2b.srcs/sources_1/bd/sbl/ip/sbl_ilmb_v10_0/sbl_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sbl_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/quyvan/Desktop/lab2b/lab2b/lab2b.srcs/sources_1/bd/sbl/ip/sbl_ilmb_v10_0/sbl_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sbl_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/quyvan/Desktop/lab2b/lab2b/lab2b.srcs/sources_1/bd/sbl/ip/sbl_ilmb_v10_0/sbl_ilmb_v10_0.xci
# IP: The module: 'sbl_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/quyvan/Desktop/lab2b/lab2b/lab2b.srcs/sources_1/bd/sbl/ip/sbl_ilmb_v10_0/sbl_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sbl_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/quyvan/Desktop/lab2b/lab2b/lab2b.srcs/sources_1/bd/sbl/ip/sbl_ilmb_v10_0/sbl_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sbl_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
